services:
  - type: web
    name: laravel-api
    runtime: docker
    dockerfilePath: docker/deployment/Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true