services:
  - type: web
    name: laravel-api
    runtime: docker
    rootDirectory: /
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: laravel_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laravel_db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: laravel_db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel_db
          property: password
      - key: PASSPORT_PASSWORD_CLIENT_ID
        generateValue: true
      - key: PASSPORT_PASSWORD_CLIENT_SECRET
        generateValue: true

  - type: pgsql
    name: laravel_db
    ipAllowList: []