services:
  - type: web
    name: laravel-api
    runtime: docker
    rootDirectory: /
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true